version: '3'
services:
  nginx-ui:
    container_name: nginx-ui
    image: schenkd/nginx-ui:latest
    ports:
      - 8080:8080
    volumes:
      - nginx:/etc/nginx

  nginx:
    container_name: nginx
    image: 172.16.130.72/basis/nginx
    ports:
      - 80:80
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx:
