---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cnf
  namespace: jira
data:
  my.cnf: |+
   [mysqld]
   character-set-server=utf8mb4
   default-time-zone='+8:00'
   max_connections=500
   innodb_lock_wait_timeout=500
   default-storage-engine=INNODB         #以下配置根据JIRA官方文档要求设置
   innodb_default_row_format=DYNAMIC     
   innodb_large_prefix=ON
   innodb_file_format=Barracuda
   innodb_log_file_size=2G
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: db-mysql
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: db-mysql
  name: db-mysql
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: db
      k8s.kuboard.cn/name: db-mysql
  serviceName: db-mysql
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: db
        k8s.kuboard.cn/name: db-mysql
    spec:
      containers:
        -
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root00--
            - name: MYSQL_ROOT_HOST
              value: '%'
          image: '172.16.130.72/basis/mysql:5.7'
          imagePullPolicy: Always
          name: mysql
          volumeMounts:
          - name: "mysql-data"
            mountPath: "/var/lib/mysql"
          - name: config-mysql
            mountPath: "/etc/mysql/conf.d"
      volumes:
      - name: config-mysql
        configMap:
          name: my-cnf 
      dnsConfig: {}
      restartPolicy: Always   
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      volumeMode: Filesystem
      storageClassName: nfs
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi