---
apiVersion: v1       ## 创建命名空间 mdm
kind: Namespace
metadata:
  name: mdm
  labels:
    name: mdm
---
apiVersion: apps/v1   
kind: Deployment
metadata:
  name: tomcat-mdm
  namespace: mdm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-mdm
  template:
    metadata:
      labels:
        app: tomcat-mdm
    spec:
      containers:
      - name: tomcat-mdm
        image: 172.16.130.72/library/tomcat-mdm-uat:v3
        readinessProbe:
          httpGet:
            path: /mdm
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /mdm
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-mdm-mysql
  namespace: mdm
spec:
  ports:
  - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service-mdm-mysql
  namespace: mdm
subsets:
  - addresses:
    - ip: 172.16.130.52
    - ip: 172.16.130.53
    - ip: 172.16.130.54
    ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: service-mdm-tomcat
  namespace: mdm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30005
  selector:
    app: tomcat-mdm
